"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)tk%8=37u*rd3vduq3fi1%rl3cc6#um%+6u3hz4)vee5bwblmg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django_filters',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    'users.apps.UsersConfig',
    'drf_spectacular',
]

MIDDLEWARE = [
    'myapp.middleware.BlockIPMiddleware',
    'myapp.middleware.LogRequestMiddleware',  # Custom middleware
    'myapp.middleware.TimerMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,   # keeps connections open; good perf
        "OPTIONS": {
            # optional: set a statement timeout (ms) to avoid runaway queries
            # "options": "-c statement_timeout=5000"
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
LOGIN_REDIRECT_URL = 'myapp:index'
LOGIN_URL = 'users:login'

MEDIA_ROOT = os.path.join(BASE_DIR,'pictures')
MEDIA_URL = '/pictures/'

#Needed for caching
CACHES = {
    "default":{
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / "cache",
    }
}

#Needed for logging


LOG_LEVEL = "DEBUG" if os.getenv("DJANGO_DEBUG", "True") == "True" else "WARNING"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "debug.log",# file that will hold all of our logs
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "DEBUG",
    },
}

#For our api's authentication
REST_FRAMEWORK = {
    #Throttling is a technique used to limit the number of requests that a client can make to an API within a certain time period. This can help prevent abuse and ensure that the API remains responsive for all users. In Django REST Framework, you can use throttling classes to implement this functionality.
    "DEFAULT_THROTTLE_CLASSES":[
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    #The "DEFAULT_THROTTLE_RATES" setting is used to specify the rate limits for different types of users in Django REST Framework. The "anon" key specifies the rate limit for anonymous users (users who are not authenticated), while the "user" key specifies the rate limit for authenticated users. In this example, anonymous users are limited to 10 requests per minute, while authenticated users are limited to 1000 requests per day. You can adjust these values as needed to suit your application's requirements.
    "DEFAULT_THROTTLE_RATES":{
        "anon": "10/minute",
        "user":"1000/day",

    },
    #Pagination is a technique used to divide large sets of data into smaller, 
    # more manageable chunks, or "pages". This can improve the performance of an 
    # API by reducing the amount of data that needs to be sent in a single response, 
    # and it can also make it easier for clients to navigate through large datasets.
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 5,

    #LimitOffsetPagination is a pagination style that allows clients to specify the number of items to return (limit) and the starting point (offset) 
    # for the items to be returned. This is useful for APIs that need to support pagination of large datasets, 
    # as it allows clients to retrieve specific subsets of data without having to load the entire dataset into memory.
    #A request example for this pagination style would be: GET /api/items/?limit=5&offset=10, which would return 5 items starting from the 11th item in the dataset.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 5,

    #This setting specifies the default filter backends that will be used for filtering querysets in the API views.
    "DEFAULT_FILTER_BACKENDS":[
        "django_filters.rest_framework.DjangoFilterBackend",
    ],

    "DEFAULT_AUTHENTICATION_CLASSES":[
        #Note that session authentication is not suitable for production environments, especially for APIs that are accessed by third-party clients. 
        # In production, you would typically use token-based authentication (like JWT) or OAuth2 for better security and scalability.
        "rest_framework.authentication.SessionAuthentication", #Type of authentiation that loads a session for different users
        'rest_framework.authentication.TokenAuthentication', #Used for token based authentication where each user is given a unique token that they can use to access the api
        "rest_framework_simplejwt.authentication.JWTAuthentication", #Used for JWT authentication where users are given a JSON Web Token that they can use to access the api
        #Jwt tokens come in two types: access tokens and refresh tokens. Access tokens are short-lived and are used to access the API, while refresh tokens are long-lived and can be used to obtain new access tokens when the old ones expire.
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'Your Project API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}
#rest_framework token - 5b5ba87c9c10a01f258fd0a81927a19990ae818b generated using 
# >>> from rest_framework.authtoken.models import Token
# >>> from django.contrib.auth.models import User
# >>> user = User.objects.get(username="joshua")
# >>> token = Token.objects.create(user=user)