# Generated by Django 6.0.1 on 2026-02-25 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_item_item_name_alter_item_item_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'item_price'], name='myapp_item_user_id_e87f8c_idx'),
        ),
    ]
